// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYV6vsyo_ZpvrX76gR5ruLC1KHl9ma2QE',
    appId: '1:133854787943:web:419241c16781157142d7c2',
    messagingSenderId: '133854787943',
    projectId: 'medi-deliver',
    authDomain: 'medi-deliver.firebaseapp.com',
    storageBucket: 'medi-deliver.appspot.com',
    measurementId: 'G-M912LHQ01Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Qlrgw_mcQEMaw8hO4uzxb0T8QU7EAAk',
    appId: '1:133854787943:android:692f9f6888e9e99542d7c2',
    messagingSenderId: '133854787943',
    projectId: 'medi-deliver',
    storageBucket: 'medi-deliver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5tshNj0lizZ1XjTh-3dvlmq_ceeGXFYc',
    appId: '1:133854787943:ios:79200d1e52430f7842d7c2',
    messagingSenderId: '133854787943',
    projectId: 'medi-deliver',
    storageBucket: 'medi-deliver.appspot.com',
    iosBundleId: 'com.example.mediDeliver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5tshNj0lizZ1XjTh-3dvlmq_ceeGXFYc',
    appId: '1:133854787943:ios:4bfc0c368161c0a042d7c2',
    messagingSenderId: '133854787943',
    projectId: 'medi-deliver',
    storageBucket: 'medi-deliver.appspot.com',
    iosBundleId: 'com.example.mediDeliver.RunnerTests',
  );
}
